/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    ALink: typeof import('@arco-design/web-vue')['Link']
    ChatWidget: typeof import('./src/components/ChatWidget.vue')['default']
    ErrorBoundary: typeof import('./src/components/ErrorBoundary.vue')['default']
    FileDragOverlay: typeof import('./src/components/FileDragOverlay.vue')['default']
    FileHeader: typeof import('./src/components/FileHeader.vue')['default']
    FileModals: typeof import('./src/components/FileModals.vue')['default']
    FilePreview: typeof import('./src/components/FilePreview.vue')['default']
    FileTable: typeof import('./src/components/FileTable.vue')['default']
    FileToolbar: typeof import('./src/components/FileToolbar.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    MarkdownRenderer: typeof import('./src/components/MarkdownRenderer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
